import Layout from "@/components/layout/Layout";
import { FileText, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

const TermsOfService = () => {
    const navigate = useNavigate();

    return (
        <Layout>
            <div className="container mx-auto px-4 py-12 max-w-4xl">
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => navigate('/')}
                    className="mb-8 gap-2 text-muted-foreground hover:text-foreground rounded-full"
                >
                    <ArrowLeft className="w-4 h-4" />
                    Back to Home
                </Button>

                <div className="flex items-center gap-3 mb-8">
                    <FileText className="w-8 h-8 text-primary" />
                    <h1 className="text-3xl md:text-4xl font-display font-bold">Terms of Service</h1>
                </div>

                <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground">
                    <p className="text-sm">Last updated: February 12, 2026</p>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using the ClawTrader platform ("Platform"), you agree to be bound by these Terms of
                            Service ("Terms"). If you do not agree to these Terms, you may not access or use the Platform.
                        </p>
                        <p>
                            ClawTrader is a decentralized application (dApp) that provides AI-powered trading agent creation,
                            autonomous trading, esports betting, and token launch services on the Monad blockchain.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">2. Eligibility</h2>
                        <p>
                            You must be at least 18 years of age to use the Platform. By using ClawTrader, you represent and
                            warrant that you meet this age requirement and that your use of the Platform complies with all
                            applicable laws in your jurisdiction.
                        </p>
                        <p>
                            You are responsible for ensuring that participation in blockchain-based trading, token activities,
                            and esports betting is legal in your jurisdiction.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">3. Platform Services</h2>
                        <h3 className="text-lg font-medium text-foreground/80">3.1 AI Trading Agents</h3>
                        <p>
                            The Platform allows you to create AI trading agents with customizable Strategy DNA parameters.
                            Agents are registered on-chain via the AgentFactory smart contract. You retain ownership of agents
                            created with your wallet address. Agent DNA values influence trading behavior but do not guarantee
                            trading performance.
                        </p>
                        <h3 className="text-lg font-medium text-foreground/80">3.2 Autonomous Trading</h3>
                        <p>
                            AI agents can execute trades on the SimpleDEX smart contract using deposited USDC. Trading decisions
                            are generated by the AI decision engine based on market data and agent DNA. All trades carry inherent
                            risk. Past performance does not guarantee future results.
                        </p>
                        <h3 className="text-lg font-medium text-foreground/80">3.3 Esports Betting</h3>
                        <p>
                            The Platform provides esports betting services using CLAW tokens on matches sourced from the PandaScore
                            API. Bets are processed through the BettingEscrow smart contract. Match results are determined by
                            real-world esports event outcomes.
                        </p>
                        <h3 className="text-lg font-medium text-foreground/80">3.4 Token Launch</h3>
                        <p>
                            Agents can launch tradeable tokens on the nad.fun bonding curve. Token launches involve on-chain
                            transactions and a deployment fee. Token prices are determined by market supply and demand through
                            the bonding curve mechanism.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">4. Wallet and Transactions</h2>
                        <p>
                            You are solely responsible for the security of your Web3 wallet and private keys. ClawTrader
                            never has access to your private keys. All blockchain transactions are irreversible once confirmed.
                            You acknowledge that:
                        </p>
                        <ul className="list-disc list-inside space-y-1 ml-4">
                            <li>Transaction fees (gas) are required for on-chain operations</li>
                            <li>Smart contract interactions carry inherent risks</li>
                            <li>Token values may fluctuate significantly</li>
                            <li>Lost wallet access cannot be recovered by ClawTrader</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">5. Risk Disclaimer</h2>
                        <p>
                            Cryptocurrency trading, token investments, and esports betting carry significant risk of financial
                            loss. By using the Platform, you acknowledge and accept the following risks:
                        </p>
                        <ul className="list-disc list-inside space-y-1 ml-4">
                            <li>AI trading agents may generate losses. DNA configuration does not guarantee profitability.</li>
                            <li>Smart contracts, while audited, may contain undiscovered vulnerabilities.</li>
                            <li>Token values on bonding curves can decrease rapidly.</li>
                            <li>Esports bet outcomes are uncertain and wagers may be lost entirely.</li>
                            <li>The Monad Testnet is a test environment; tokens have no real-world value.</li>
                            <li>Market conditions, network congestion, and external factors may affect transactions.</li>
                        </ul>
                        <p className="font-medium text-foreground">
                            Never invest more than you can afford to lose. ClawTrader is not a financial advisor.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">6. Prohibited Activities</h2>
                        <p>You agree not to:</p>
                        <ul className="list-disc list-inside space-y-1 ml-4">
                            <li>Use the Platform for money laundering, fraud, or other illegal activities</li>
                            <li>Attempt to exploit, hack, or manipulate smart contracts</li>
                            <li>Interfere with the Platform's infrastructure or other users' experience</li>
                            <li>Create agents or tokens for deceptive or harmful purposes</li>
                            <li>Use automated tools to abuse API rate limits or scrape platform data</li>
                            <li>Circumvent any security measures implemented by the Platform</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">7. Intellectual Property</h2>
                        <p>
                            The ClawTrader platform, including its design, codebase, smart contracts, and branding, is
                            licensed under the MIT License. AI agents you create are associated with your wallet address.
                            Tokens launched through the Platform are subject to their own market dynamics.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">8. Limitation of Liability</h2>
                        <p>
                            To the maximum extent permitted by law, ClawTrader and its contributors shall not be liable for
                            any indirect, incidental, special, consequential, or punitive damages arising from your use of
                            the Platform, including but not limited to:
                        </p>
                        <ul className="list-disc list-inside space-y-1 ml-4">
                            <li>Trading losses incurred by AI agents</li>
                            <li>Lost bets on esports matches</li>
                            <li>Token value depreciation</li>
                            <li>Smart contract failures or vulnerabilities</li>
                            <li>Network outages or blockchain congestion</li>
                            <li>Unauthorized access to your wallet</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">9. Modifications</h2>
                        <p>
                            We reserve the right to modify these Terms at any time. Updated Terms will be posted on this page
                            with a revised date. Continued use of the Platform after changes constitutes acceptance of the
                            updated Terms.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">10. Governing Law</h2>
                        <p>
                            These Terms shall be governed by and construed in accordance with applicable laws, without regard
                            to conflict of law principles. Any disputes shall be resolved through good-faith negotiation before
                            pursuing formal legal remedies.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-xl font-semibold text-foreground">11. Contact</h2>
                        <p>
                            For questions about these Terms of Service, please reach out through our GitHub repository
                            or community channels.
                        </p>
                    </section>
                </div>
            </div>
        </Layout>
    );
};

export default TermsOfService;
